sudo: required
dist: xenial
addons:
  apt:
    packages:
      - openssl
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.7'
install:
- pip install -r requirements.txt
- openssl version -a
script:
- nosetests --with-coverage --cover-package=paypalrestsdk --include=paypalrestsdk/* --exclude=functional*

