sudo: required
dist: trusty
addons:
  apt:
    packages:
      - openssl
language: python
python:
- '2.7'
- '3.3'
- '3.4'
install:
- pip install --upgrade pip wheel setuptools
- pip install -r requirements.txt
- openssl version -a
script:
- python -W ignore -m unittest paypalrestsdk tests
