sudo: required
dist: trusty
addons:
  apt:
    packages:
      - openssl
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install --upgrade pip wheel setuptools
- pip install -r requirements.txt
- openssl version -a
script:
- nosetests tests/core
notifications:
  email:
    recipients:
      - external-ci-notifications+braintreehttp@getbraintree.com
    on_success: change
